name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v2.0.1 등의 태그 푸시 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: iptime-manager-linux
            asset_name: iptime-manager-linux-amd64
          - os: macos-latest
            artifact_name: iptime-manager-macos
            asset_name: iptime-manager-macos-amd64
          - os: windows-latest
            artifact_name: iptime-manager-windows
            asset_name: iptime-manager-windows-amd64.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller \
          --name iptime-manager \
          --onefile \
          --clean \
          --noconfirm \
          --add-data "src:src" \
          --hidden-import requests \
          --hidden-import urllib3 \
          --hidden-import certifi \
          --hidden-import charset_normalizer \
          --hidden-import idna \
          --strip \
          iptime_cli.py
        
        # 실행 권한 부여
        chmod +x dist/iptime-manager
        
        # 이름 변경
        mv dist/iptime-manager dist/${{ matrix.asset_name }}

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller `
          --name iptime-manager `
          --onefile `
          --clean `
          --noconfirm `
          --add-data "src;src" `
          --hidden-import requests `
          --hidden-import urllib3 `
          --hidden-import certifi `
          --hidden-import charset_normalizer `
          --hidden-import idna `
          iptime_cli.py
        
        # 이름 변경
        move dist\iptime-manager.exe dist\${{ matrix.asset_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # 태그 푸시일 때만 릴리스 생성

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Display structure of downloaded files
      run: ls -R ./artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## iptime-manager ${{ github.ref_name }}
          
          ### 다운로드
          
          아래에서 운영체제에 맞는 파일을 다운로드하세요:
          - **Linux**: `iptime-manager-linux-amd64`
          - **macOS**: `iptime-manager-macos-amd64`
          - **Windows**: `iptime-manager-windows-amd64.exe`
          
          ### 사용법
          
          #### Linux/macOS
          ```bash
          chmod +x iptime-manager-*
          ./iptime-manager-* --help
          ```
          
          #### Windows
          ```cmd
          iptime-manager-windows-amd64.exe --help
          ```
          
          ### 변경사항
          
          이 릴리스의 변경사항은 [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)를 참조하세요.
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/iptime-manager-linux/iptime-manager-linux-amd64
        asset_name: iptime-manager-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/iptime-manager-macos/iptime-manager-macos-amd64
        asset_name: iptime-manager-macos-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/iptime-manager-windows/iptime-manager-windows-amd64.exe
        asset_name: iptime-manager-windows-amd64.exe
        asset_content_type: application/octet-stream
